export const DB_USER = process.env.DB_USER || 'root'
export const DB_PASSWORD = process.env.DB_PASSWORD || 'Importante16'
export const DB_NAME = process.env.DB_NAME || 'databse_production'
export const DB_HOST = process.env.DB_HOST || '127.0.0.1'
export const DB_DIALECT = process.env.DB_DIALECT || 'mysql'